### ISSUE TITLE
error when build module in android studio

### ISSUE THREAD

**Issue by xiaokang-huang** [googlesamples/vulkan-basic-samples#12]
Hi
when I start to build some module, such as device or drawcube in android studio (in step 4), I got error message as below. how can i solve it? thank you.

Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':LunarGSamples/API-Samples/android/:drawcube:externalNativeBuildDebug'.
> Build command failed.
  Error while executing '/home/huangxk/sourcecode/android-sdk-linux/cmake/3.6.3155560/bin/cmake' with arguments {--build /home/huangxk/sourcecode/from_net/vulkan-basic-samples/LunarGSamples/API-Samples/android/drawcube/.externalNativeBuild/cmake/debug/x86 --target vulkan_sample}
  [1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/x86/libvulkan_sample.so
  FAILED: : && /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  -target i686-none-linux-android -gcc-toolchain /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64 --sysroot=/home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/platforms/android-24/arch-x86 -fPIC -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -fno-exceptions -fno-rtti  -std=c++11  -Werror -D VK_USE_PLATFORM_ANDROID_KHR -O0 -fno-limit-debug-info -O0 -fno-limit-debug-info  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libvulkan_sample.so -o ../../../../build/intermediates/cmake/debug/obj/x86/libvulkan_sample.so CMakeFiles/vulkan_sample.dir/home/huangxk/sourcecode/from_net/vulkan-basic-samples/LunarGSamples/API-Samples/drawcube/drawcube.cpp.o CMakeFiles/vulkan_sample.dir/vulkan_wrapper/vulkan_wrapper.cpp.o  -llog utils/libvsamputils.a /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a -landroid -llog utils/libnative_app_glue.a -lm "/home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/libgnustl_static.a" && :
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function (anonymous namespace)::CompileToSpecifiedOutputType(shaderc_compiler*, char const*, unsigned int, shaderc_shader_kind, char const*, char const*, shaderc_compile_options*, shaderc_util::Compiler::OutputType): error: undefined reference to 'std::__ndk1::ios_base::init(void*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function (anonymous namespace)::CompileToSpecifiedOutputType(shaderc_compiler*, char const*, unsigned int, shaderc_shader_kind, char const*, char const*, shaderc_compile_options*, shaderc_util::Compiler::OutputType): error: undefined reference to 'std::__ndk1::locale::locale()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function (anonymous namespace)::CompileToSpecifiedOutputType(shaderc_compiler*, char const*, unsigned int, shaderc_shader_kind, char const*, char const*, shaderc_compile_options*, shaderc_util::Compiler::OutputType): error: undefined reference to 'shaderc_util::Compiler::Compile(shaderc_util::string_piece const&, EShLanguage, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::function<EShLanguage (std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >*, shaderc_util::string_piece const&)> const&, shaderc_util::CountingIncluder&, shaderc_util::Compiler::OutputType, std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >*, unsigned int*, unsigned int*, shaderc_util::GlslInitializer*) const'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function (anonymous namespace)::CompileToSpecifiedOutputType(shaderc_compiler*, char const*, unsigned int, shaderc_shader_kind, char const*, char const*, shaderc_compile_options*, shaderc_util::Compiler::OutputType): error: undefined reference to 'shaderc_util::Compiler::Compile(shaderc_util::string_piece const&, EShLanguage, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::function<EShLanguage (std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >*, shaderc_util::string_piece const&)> const&, shaderc_util::CountingIncluder&, shaderc_util::Compiler::OutputType, std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >*, unsigned int*, unsigned int*, shaderc_util::GlslInitializer*) const'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function (anonymous namespace)::CompileToSpecifiedOutputType(shaderc_compiler*, char const*, unsigned int, shaderc_shader_kind, char const*, char const*, shaderc_compile_options*, shaderc_util::Compiler::OutputType): error: undefined reference to 'std::__ndk1::locale::~locale()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function (anonymous namespace)::CompileToSpecifiedOutputType(shaderc_compiler*, char const*, unsigned int, shaderc_shader_kind, char const*, char const*, shaderc_compile_options*, shaderc_util::Compiler::OutputType): error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function shaderc_assemble_into_spv: error: undefined reference to 'shaderc_util::SpirvToolsAssemble(shaderc_util::string_piece, spv_binary_t**, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function shaderc_parse_version_profile: error: undefined reference to 'shaderc_util::ParseVersionProfile(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, int*, EProfile*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > >::rehash(unsigned int): error: undefined reference to 'std::__ndk1::__next_prime(unsigned int)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > >::rehash(unsigned int): error: undefined reference to 'std::__ndk1::__next_prime(unsigned int)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > > >::__rehash(unsigned int): error: undefined reference to 'std::logic_error::logic_error(char const*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::~basic_stringstream(): error: undefined reference to 'std::__ndk1::locale::~locale()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::~basic_stringstream(): error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char> >::~basic_istream(): error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char> >::~basic_istream(): error: undefined reference to 'std::__ndk1::ios_base::~ios_base()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::~basic_stringstream(): error: undefined reference to 'std::__ndk1::locale::~locale()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(shaderc.o):function non-virtual thunk to std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::~basic_stringstream(): error: undefined reference to 'std::__ndk1::locale::~locale()'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(reflection.o):function void std::__ndk1::vector<glslang::TObjectReflection, std::__ndk1::allocator<glslang::TObjectReflection> >::__push_back_slow_path<glslang::TObjectReflection>(glslang::TObjectReflection&&): error: undefined reference to 'std::logic_error::logic_error(char const*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(reflection.o):function std::__ndk1::__hash_table<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > > >::rehash(unsigned int): error: undefined reference to 'std::__ndk1::__next_prime(unsigned int)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(reflection.o):function std::__ndk1::__hash_table<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > > >::rehash(unsigned int): error: undefined reference to 'std::__ndk1::__next_prime(unsigned int)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(reflection.o):function std::__ndk1::__hash_table<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > >, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, glslang::pool_allocator<char> > > >::__rehash(unsigned int): error: undefined reference to 'std::logic_error::logic_error(char const*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(binary.o):function spvBinaryParse: error: undefined reference to 'spvTakeFirstMatchableOperand(std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(binary.o):function spvBinaryParse: error: undefined reference to 'spvPrependOperandTypes(spv_operand_type_t const*, std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(binary.o):function spvBinaryParse: error: undefined reference to 'spvPrependOperandTypes(spv_operand_type_t const*, std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(assembly_grammar.o):function libspirv::AssemblyGrammar::prependOperandTypesForMask(spv_operand_type_t, unsigned int, std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*) const: error: undefined reference to 'spvPrependOperandTypesForMask(spv_operand_table_t const*, spv_operand_type_t, unsigned int, std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(operand.o):function std::__ndk1::deque<spv_operand_type_t, std::__ndk1::allocator<spv_operand_type_t> >::__add_front_capacity(unsigned int): error: undefined reference to 'std::logic_error::logic_error(char const*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(text.o):function spvTextEncodeOperand(libspirv::AssemblyGrammar const&, libspirv::AssemblyContext*, spv_operand_type_t, char const*, spv_instruction_t*, std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*): error: undefined reference to 'spvAlternatePatternFollowingImmediate(std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> > const&)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(text.o):function spvTextEncodeOperand(libspirv::AssemblyGrammar const&, libspirv::AssemblyContext*, spv_operand_type_t, char const*, spv_instruction_t*, std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*): error: undefined reference to 'spvPrependOperandTypes(spv_operand_type_t const*, std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*)'
  /home/huangxk/sourcecode/android-sdk-linux/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a(text.o):function spvTextToBinary: error: undefined reference to 'spvExpandOperandSequenceOnce(spv_operand_type_t, std::deque<spv_operand_type_t, std::allocator<spv_operand_type_t> >*)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ggfan** [comment]
Yeah, you just found a doc bug: step 4 should be read something as: import from root of the repo.

The file directory structure was changed last time while updating with CMake build system,  forgot to update the instruction.  May you kindly try it out and confirm? 

will update the instructions accordingly.  thank you

**Comment by xiaokang-huang** [comment]
still can't work for this issue, I got the same message when building module.
Besides, I found another one. In step 3, before running script "cmake -DANDROID=ON -DANDROID_ABI=[armeabi-v7a|arm64-v8a|x86|x86_64|all(default)]", I need to modify LunarGSamples/CMakeLists.txt, in line 216
chang "add_subdirectory(demos)" to "add_subdirectory(Demos)". 
I found in my directory, I have both demos and Demos folder, but demos is empty

**Comment by ggfan** [comment]
thanks: there was some change in the upstream between now and then. The doc need to be changed to for step3: it is actually just optional: once get from repo, it is ready to build, do not need to regenerate those files. which OS are you at?  I tried on Mac today, it was ok ( gradle complains asking to upgrade version, other than that it was ok )

**Comment by ggfan** [comment]
Maybe just do: git clean -xdf; git reset --hard.  The re-import the project into android. need Android Studio 2.2+ and above, with cmake plugin installed. If you still have problem, we should look more at the environment. If you are on windows, meed to install NDK under root directory I think ( otherwise it is 240 character path limit thing)

**Comment by tpalli** [comment]
I'm getting same or similar linker errors as well. Android Studio is up to date and git repository is a clean clone. I'm getting loads of undefined references to std::__ndk1::locale, std::__ndk1::ios_base type of functions. All of these errors come from shaderc linking. I'm building on Linux (ubuntu 16.04).

**Comment by tpalli** [comment]
but now I found a way to get rid of this issue, I removed built symbols (from some previous builds?) for shaderc under NDK (libs, include, obj), made sure it recompiled itself and now things work ok :)

**Comment by ggfan** [comment]
Ok, that is something I do not know; thank you for your sharing of experience: yeah I will take a look later (a little distracted with a few ( not just 1 or 2 ) nowadays ) and report out.  One thing with earlier of android studio is that: I need to manually remove ${project_dir}/{module_dir}/.externalNativeBuild directory when things went wrong.

**Comment by ggfan** [comment]
The source is updated with upstream: all those issues should addressed  -- in a sense that the instruction tells to generate files from API-Samples directory. So demos etc and up directories will not be included, so no errors from that.

will look at the upstream for future issues and fix them there at:  git@github.com:LunarG/VulkanSamples.git.

**Comment by Necktwi** [comment]
@tpalli how to make `shaderc` to recompile itself? I have delete `shaderc/libs/*`, `shaderc/obj/*` and rebuilt `15-draw_cube` and it says
`Error:error: '/Users/me/Library/Android/sdk/ndk-bundle/sources/third_party/shaderc/libs/gnustl_static/x86/libshaderc.a', needed by '../../../../build/intermediates/cmake/debug/obj/x86/libvulkan_sample.so', missing and no known rule to make it`

**Comment by ggfan** [comment]
yeah, just rebuild the shaderc binary in your NDK -- Step 1 in
   https://github.com/googlesamples/vulkan-basic-samples
The command itself is:
`../../../ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_STL:=[gnustl_static|gnustl_shared|c++_static|c++_shared] APP_ABI=[armeabi-v7a|arm64-v8a|x86|x86_64|all] libshaderc_combined -j16`

after that you should be able to see it inside your "./libs" folder, rebuild sample should be ok.

**Comment by Necktwi** [comment]
just recompiling them worked. I don't understand what you meant by "recompile itself"

**Comment by ggfan** [comment]
Oh, "The command itself is"  is the real command to build shaderc on linux / mac OS.  sorry for the confusion.
