### ISSUE TITLE
Created Descriptor Pool Error after vkCreateDescriptorPool

### ISSUE THREAD

**Issue by felknight** [googlesamples/vulkan-basic-samples#13]
In version of commit:

126dd6d on Apr 4, 2016
@hak hak Move files under LunarGSamples again. 

At: https://github.com/googlesamples/vulkan-basic-samples/blob/master/LunarGSamples/layers/core_validation.cpp#L6710

The layer returns error on a perfect valid call whenever the LOG function returns a true value.
I'm pretty sure thats a misstyping.

I suspect the info log was confused with a log error.

Besides the format its diferente from other infos in the layer:

```
OBJ[0x4] : CREATE Device object 0xe109a0
OBJ[0x5] : CREATE Queue object 0xe85240
OBJ[0x6] : CREATE Command Pool object 0x1
OBJ[0x7] : CREATE Render Pass object 0x2
OBJ[0x8] : CREATE Shader Module object 0x3
OBJ[0x9] : CREATE Shader Module object 0x4
OBJ[0xa] : CREATE Descriptor Set Layout object 0x5
OBJ[0xb] : CREATE Pipeline Layout object 0x6
OBJ[0xc] : CREATE Pipeline object 0x7
Created Descriptor Pool 0x8
OBJ[0xd] : CREATE Descriptor Pool object 0x8
OBJ[0xe] : CREATE Image object 0x9
OBJ[0xf] : CREATE Device Memory object 0xa
OBJ[0x10] : CREATE Image View object 0xb
OBJ[0x11] : CREATE Framebuffer object 0xc

```

**Comment by ggfan** [comment]
Could you look at this file to see it is already fixed?
 https://github.com/LunarG/VulkanSamples/blob/master/layers/core_validation.cpp 
if it still there, could fix it in upstream.  thx

**Comment by tobine** [comment]
Created [PR1674](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1674) in LVL repo to fix this issue.

**Comment by ggfan** [comment]
@felknight, thank you so much for filing this bug!!  it is real one and will be in the upstream repo.  Appreciate your help, and keep it going!

for future bugs you found, you may file it to the upstream: 
https://github.com/LunarG/VulkanSamples

 or here, make sure to add one of our names here -- somehow  I did not notification for any new issues in this repo here. will try to fix it.

**Comment by ggfan** [comment]
the upstream fix is merged: It will come down to this branch soon. Closing down this one and let the process run its own course.  It is really good bug, thanks!
