### ISSUE TITLE
Application terminates on one plus 5

### ISSUE THREAD

**Issue by Necktwi** [googlesamples/vulkan-basic-samples#19]
I have successfully built **VulkanAPIsamples** but the application terminates immediately.

```
07/17 22:36:40: Launching 15-draw_cube
$ adb shell am start -n "com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/android.app.NativeActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 32673 on device oneplus-oneplus_a5000-d86ee81a
Application terminated.
```
when debugging

```
07/17 22:40:51: Launching 15-draw_cube
$ adb shell am start -n "com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/android.app.NativeActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube.test | com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube
Connecting to com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube
Now Launching Native Debug Session
Starting LLDB server: /data/data/com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/lldb/bin/start_lldb_server.sh /data/data/com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/lldb unix-abstract /data/data/com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/lldb/tmp platform-1500311452120.sock "lldb process:gdb-remote packets"
$ adb shell cat /data/local/tmp/lldb-server | run-as com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube sh -c 'cat > /data/data/com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/lldb/bin/lldb-server && chmod 700 /data/data/com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/lldb/bin/lldb-server'
$ adb shell cat /data/local/tmp/start_lldb_server.sh | run-as com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube sh -c 'cat > /data/data/com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/lldb/bin/start_lldb_server.sh && chmod 700 /data/data/com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube/lldb/bin/start_lldb_server.sh'
Connected to the target VM, address: 'localhost:8603', transport: 'socket'
Disconnected from the target VM, address: 'localhost:8603', transport: 'socket'
```
there are no logs.

oneplus5 android 7.1.1

**Comment by ggfan** [comment]
you might find another bug here.  May you set up a breakpoint in initVulkan() to see whether get it: 
  API-Samples/android/vulkan_wrapper/vulkan_wrapper.h:int InitVulkan(void)

it is a guess -- not sure it will be useful at all.

**Comment by Necktwi** [comment]
It didn't help. I was able to debug the template ndk project("Hello from C++") though.

**Comment by ggfan** [comment]
Ok, does it call InitVulkan()?  I was wondering if Vulkan is supported on that phone ( by all means it should, it is the latest one ).   if Vulkan is not supported, InitVulkan() will fail. may you confirm?

**Comment by Necktwi** [comment]
I have put the breakpoints at `android_main`, `sample_main` and `InitVulkan`. Application terminates before the breakpoints. I have poured my savings in to the phone to run these samples!

**Comment by Necktwi** [comment]
`GOF 3` vulkan based game is running on my phone. so it should `InitVulkan()`

**Comment by ggfan** [comment]
Ok, looks we have something needed to take care of. 
change the applicationId in your build.gradle for 15-draw_cube to be shorter ( future android studio will be able to take care of longer appID/packageId ):
        applicationId 'com.google.vulkan.samples.org.khronos.vulkan.samples.T15_draw_cube'
make it to something shorter ( less than 60 characters -- remove either google part or khronos part in the name). This one has been take care of in the upstream repo,  it needs to be populated down. will do it

then clean and rebuild, if you are using NDK-R15, there is another complication, you will see a build error for app_dummy(); just remove
  -Werror  in utils/CMakeLists.txt from CMAKE_CXX_FLAGS
( this has not been done in upstream yet )

clean it and rebuild, set breakpoint and see how it goes.

this should get us to somewhere. But if you could not run the app at all,  the above will not solve the problem -- we need to step back a little more.

after you build the APK ( android studio, "Build" --> "Build APK"), adb push -r your-newly-build-apk  to your phone, and start it manually from your phone, see how it goes.  This would remove any abnormal things from Android Studio.

also put your ndk/studio version if the above does not help.  If all that fails, download this repo
  https://github.com/googlesamples/android-vulkan-tutorials
and try any one of it -- it is small and independent. easier to shoot away the build environment problems.  After you could successfully run that, we could come back to this one ( this one has too much interweaving, but it is complete)

**Comment by ggfan** [comment]
adding a PullRequest to update this repo from upstream:
  https://github.com/googlesamples/vulkan-basic-samples/pull/20

**Comment by ggfan** [comment]
please re-sync with the github and see if it is better ( suppose to fix the debugging issue )

thx

**Comment by Necktwi** [comment]
removing `-Werror` and shortening app id did the trick. didn't try to git pull; I have created it by new sample in android studio. I have previously changed `build.gradle` to

```
    compileSdkVersion 25
    buildToolsVersion '26.0.0'
    defaultConfig {
        applicationId 'com.google.vulkan.samples.khronos.T15_draw_cube'
        minSdkVersion 25
        targetSdkVersion 25
        versionCode 1
        versionName '0.0.1'
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_PLATFORM=android-26', '-DANDROID_TOOLCHAIN=clang',
                        "-DANDROID_STL=${stlType}", '-DSAMPLE_NAME=' + project.getName()
            }
        }
    }
```
