### ISSUE TITLE
Misleading shaderc compilation command on developer.android.com

### ISSUE THREAD

**Issue by pumexx** [googlesamples/vulkan-basic-samples#26]
It's nice that you have proper command for shaderc compilation in README.md, but most of the people will probably try to compile shaderc using a command found on developer.android.com : 

https://developer.android.com/ndk/guides/graphics/getting-started

The command for compiling shaderc ON WINDOWS is missing this piece : "APP_STL=c++_static"
and as a result compiler is unable to find standard C++ headers ( <sstream> to be precise ).

**Comment by ggfan** [comment]
thank you for issue, let me give it a shot to fix it

internal CL is: cl/227804363. please take a look if you have access, thanks!

**Comment by ggfan** [comment]
CL is merged, it should be visible in the next doc publish cycle
