### ISSUE TITLE
Cannot build: shaderc/env.h not found

### ISSUE THREAD

**Issue by djnotes** [googlesamples/vulkan-basic-samples#32]
I am unable to build the samples. There are no syntax errors or similar things, but when I hit Build APKs, I get the following error:  

> Fatal error: shaderc/env.h not found.   

More complete build output:  

> In file included from /home/johndoe/src/VulkanAPIsamples/API-Samples/utils/util.cpp:44:
> In file included from /home/johndoe/.local/AndroidSdk/ndk/21.0.5935234/sources/third_party/shaderc/include/shaderc/shaderc.hpp:22:
> /home/johndoe/.local/AndroidSdk/ndk/21.0.5935234/sources/third_party/shaderc/include/shaderc/shaderc.h:26:10: fatal error: 'shaderc/env.h' file not found
> 

Build information: 
OS: Fedora 31
Android Studio version: 4.0 Canary 4
NDK version: 21.0.5935234

**Comment by ggfan** [comment]
I saw this here:  https://github.com/android/ndk/issues/1105, seems they are working on it ( or already closed ).  we should follow up on that one.
