### ISSUE TITLE
How Vulkan render real-time stream yuv data?

### ISSUE THREAD

**Issue by huyu0415** [googlesamples/vulkan-basic-samples#33]
There is a question, how to render the real-time stream of Yuv420, just like the Yuv data decoded by MediaCodec, how to render it in real time. Can vulkan render real-time yuv data like gl2_yuvtex.cpp in the source code?

**Comment by ggfan** [comment]
sorry for the delay.  VK_KHR_sampler_ycbcr_conversion is the one to use: it is in  Vulkan 1.1 now, most newly launched Android devices would support the feature.
