### ISSUE TITLE
cmakes.. error and makefile missing

### ISSUE THREAD

**Issue by Azaretdodo** [googlesamples/vulkan-basic-samples#34]
Hello,

What I happening when I want build your GitHub :

![CMakesdotdotErrorAndMakeFilesMissing](https://user-images.githubusercontent.com/30596513/81473977-ba375600-9202-11ea-96c3-e6cf9c605217.jpg)

Thank you in advance to help myself fully install your GitHub,

Regards.

Azaretdodo.

**Comment by Azaretdodo** [comment]
I have fully install X11 by autoconf autoheader commands line from this GitHub link :

https://github.com/xmonad/X11

I Don't know why I keep the X11 error It should be a false error,

Regards.


Azaretdodo.

**Comment by Azaretdodo** [comment]
finaly thank you to bring a makefile,

Regards.


Azaretdodo.

**Comment by ggfan** [comment]
Yeah, please try the upstream repo: https://github.com/LunarG/VulkanSamples
