### ISSUE TITLE
I am happening this error in layer subdirectory

### ISSUE THREAD

**Issue by Azaretdodo** [googlesamples/vulkan-basic-samples#35]
Hello,

I am happening this error in layer subdirectory : 

![ErrorByCMakeDotDotCommandLine](https://user-images.githubusercontent.com/30596513/81492942-7db83880-929c-11ea-9f42-80d5f18a9166.jpg)

Thank you in advance to repair the problem,

Regards.

Azaretdodo.

**Comment by Azaretdodo** [comment]
It missing a makefile in layer subdirectory

**Comment by ggfan** [comment]
could you please use the layers inside the upstream repo:
  https://github.com/LunarG/VulkanSamples

This repo was meant for the API samples, and have not updated from upstream for a while.  please use the upstream repo:  https://github.com/LunarG/VulkanSamples
