### ISSUE TITLE
Support setting Android ABI with cmake on Windows

### ISSUE THREAD

**Issue by qchong** [googlesamples/vulkan-basic-samples#9]
In the [Vulkan Getting Started guide](https://developer.android.com/ndk/guides/graphics/getting-started.html#testing), this command works for Linux and Mac:

`$ cmake -DANDROID=ON -DANDROID_ABI=[armeabi-v7a|arm64-v8a| x86|x86_64|all(default)]`

However, running the equivalent command in Windows returns errors: e.g.

```
c:\dev\github-projects\vulkan-basic-samples\LunarGSamples\API-Samples>"c:\Program Files\CMake\bin\cmake"  -DANDROID=ON -DANDROID_ABI=armeabi-v7a
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error in CMakeLists.txt:
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error in CMakeLists.txt:
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/dev/github-projects/vulkan-basic-samples/LunarGSamples/API-Samples/CMakeFiles/CMakeOutput.log".
See also "C:/dev/github-projects/vulkan-basic-samples/LunarGSamples/API-Samples/CMakeFiles/CMakeError.log".
```

Please provide an equivalent way to do this in Windows without requiring users to install VS.

**Comment by ggfan** [comment]
thank you for the report: it is real and interesting issue, now I realized, in a sense:

- The cmake we are using to generate Android project files is NOT the cmake that comes with sdk/ndk.  It is generic one that in the path on the host ( MacOS, Linux, or windows )
- The CMakeLists.txt file(s) used to generate project files ( desktop and Android ) has auto-detection for the compiler to use. We have been using whatever on the host the compiler it is to bypass the check [ we did not used the cross-compiler for Android packed inside NDK for this purpose]. On the platforms used to generate Android project files, compiler ( desktop version ) is pre-installed so we used those, then checked in the code into github. So for windows platform, it is implied that we have to have certain compiler installed ( or set up the right cmake CC/CXX macros to use NDK's cross-platform ones ).

Before that, windows platform would not be able to generate Android Studio project files; it is not that bad though -- all Android Project are already inside github repo, no need to re-generate it if default stl-type (gnustl-static) is ok.

**Comment by ggfan** [comment]
updated docs:
done: updated to [README.md](https://github.com/googlesamples/vulkan-basic-samples/blob/master/README.md)  and [wiki page](https://github.com/googlesamples/vulkan-basic-samples/wiki/Updating-project-file)

please check it out.  thanks

**Comment by qchong** [comment]
I've reviewed the README.md (https://github.com/googlesamples/vulkan-basic-samples/blob/master/README.md) and the Wiki page (https://github.com/googlesamples/vulkan-basic-samples/wiki/Updating-project-file).

For README.md:
* It's not clear if the 'Build shaderc for NDK' step is required or optional. In the [Getting Started guide](https://developer.android.com/ndk/guides/graphics/getting-started.html#downloading), it's indicated as optional. In the Readme, however, it seems to be required.
* Some minor doc issues such as typos and grammar. I've created a PR [here](https://github.com/googlesamples/vulkan-basic-samples/pull/18) with suggested fixes. 

For the wiki page:
* Similar comment as above about whether building shaderc is required or optional.
* For the build command for shaderc, suggest modifying the command to list all valid options for `APP_STL`:
```
../../../ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_STL:=[gnustl_static|gnustl_shared|c++_static|c++_shared] APP_ABI=[armeabi-v7a|arm64-v8a|x86|x86_64|all] libshaderc_combined -j16 
```
* Step 3 cannot be run as-is on Windows. Please update this section with the Windows-specific steps.
    * The `-s` and `-g` command options are unrecognized by Windows. Should this be `--sync-glslang` and `--build-glslang`?
    * I still see an error if Visual Studio is not installed. See example of the error output [here](https://gist.github.com/qchong/4ec3c00c8c6ba04544335fd60d3eb381).

**Comment by ggfan** [comment]
1) as of today: building shaderc is a MUST
2) On windows, need to follow the upstream windows instruction to set up the machine,  then do android specific steps in this repo.  in other words, this repo's instruction is Additional steps to the upstream instruction for Windows.

**Comment by ggfan** [comment]
again, on Windows, steps inside "[Windows System Requirements](https://github.com/LunarG/VulkanSamples)" must be followed before updating project, if you choose to update it.

**Comment by ggfan** [comment]
closing down this, reopen when necessary. Thanks
